apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: AUTHOR
          value: "{{ .Values.env.AUTHOR }}"
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.livenessProbe.path }}
            port: {{ .Values.probes.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readinessProbe.path }}
            port: {{ .Values.probes.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
      imagePullSecrets:
      - name: my-docker-secret