apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
  namespace: my-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJhdm9pZG9ja2VyIiwKICAgICAgInBhc3N3b3JkIjogImRja3JfcGF0X1hZV2JVZEhTb3YweE5jbmxIeXV0TlNOU0t2SSIsCiAgICAgICJlbWFpbCI6ICJuaWtpdGthX2tvbnlraG92QG1haWwucnUiCiAgICB9CiAgfQp9Cg==
